// OpenCode adapter. Formats from opencode.ai/docs (commands, agents, plugins, tools, rules), checked 2026-09-24.
// OpenCode reads AGENTS.md itself, so no extra rules file is needed.
import type { CoreFiles } from "../core.js";
import { commandsOf, rolesOf, sortedByPath, yamlValue } from "./shared.js";

// OpenCode permission keys each role's subagent is denied. "edit" covers edit, write and apply_patch.
const ROLE_DENY: Record<string, string[]> = {
  planner: ["bash"],
  tester: [],
  implementer: [],
  reviewer: ["edit"],
};

// Runs Groundwork's guards before each tool call. Throwing blocks the call.
const GUARD_PLUGIN = `// Groundwork: runs the guards listed in .groundwork/config.json before each tool call.
// Throwing an error blocks the call. Generated by Groundwork; edit .groundwork/guards/ instead.
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { pathToFileURL } from "node:url";

export const GroundworkGuards = async ({ directory }) => {
  const guardsDir = join(directory, ".groundwork", "guards");
  const configPath = join(directory, ".groundwork", "config.json");
  const runner = await import(pathToFileURL(join(guardsDir, "run.mjs")).href);

  return {
    "tool.execute.before": async (input, output) => {
      const guards = existsSync(configPath) ? (JSON.parse(readFileSync(configPath, "utf8")).guards ?? []) : [];
      if (guards.length === 0) return;
      const action = runner.toAction("opencode", { tool: input.tool, args: output.args ?? {} });
      if (!action) return;
      const result = await runner.runGuards(action, guards, guardsDir);
      if (result.block) throw new Error(result.reason);
    },
  };
};
`;

// Pure: core files in, OpenCode files out. Generated files point to the core instead of copying it.
export function generateOpenCode(core: CoreFiles): Record<string, string> {
  const out: Record<string, string> = {};

  for (const { name, description } of commandsOf(core)) {
    out[`.opencode/commands/${name}.md`] = [
      "---",
      `description: ${yamlValue(description)}`,
      "---",
      `Read \`.groundwork/commands/${name}.md\` now and follow it exactly.`,
      "",
      "Arguments: $ARGUMENTS",
      "",
    ].join("\n");
  }

  for (const { name: role, description } of rolesOf(core)) {
    const deny = ROLE_DENY[role];
    if (!deny) throw new Error(`No OpenCode permissions defined for role "${role}"`);
    out[`.opencode/agents/gw-${role}.md`] = [
      "---",
      `description: ${yamlValue(description)}`,
      "mode: subagent",
      ...(deny.length > 0 ? ["permission:", ...deny.map((key) => `  ${key}: deny`)] : []),
      "---",
      `You are the Groundwork ${role}. Read \`.groundwork/roles/${role}.md\` now and follow it exactly.`,
      "Load only the files it lists under Load.",
      "",
    ].join("\n");
  }

  out[".opencode/plugins/groundwork-guards.js"] = GUARD_PLUGIN;

  return sortedByPath(out);
}
