// OpenCode adapter. Formats from opencode.ai/docs (commands, agents, tools, rules), checked 2026-09-24.
// OpenCode reads AGENTS.md itself, so no extra rules file is needed.
import type { CoreFiles } from "../core.js";
import { commandsOf, modelFor, rolesOf, sortedByPath, yamlValue, type ModelHints } from "./shared.js";

// OpenCode permission keys each role's subagent is denied. "edit" covers edit, write and apply_patch.
const ROLE_DENY: Record<string, string[]> = {
  planner: ["bash"],
  tester: [],
  implementer: [],
  reviewer: ["edit"],
};

// Runs Groundwork's guards before each tool call (throwing blocks the call), and adds the
// session-start orientation to the system prompt, like Claude Code's SessionStart hook.
// OpenCode 2.x plugin format: a default export { id, setup }, with hooks registered on the context.
// Guards checked against OpenCode 2.0.16 on 2026-09-25. The "context" session hook, whose system
// entries must be { type: "text", text }, checked against 2.0.18 on 2026-09-26.
const GUARD_PLUGIN = `// Groundwork: runs the guards listed in .groundwork/config.json before each tool call, and tells
// each new session where the project stands (from .groundwork/HANDOFF.md).
// Throwing an error blocks the call. Generated by Groundwork; edit .groundwork/guards/ instead.
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

// This file lives in <project>/.opencode/plugins/, so the project is two folders up.
const project = fileURLToPath(new URL("../../", import.meta.url));

export default {
  id: "groundwork-guards",
  setup: async (context) => {
    const guardsDir = join(project, ".groundwork", "guards");
    const configPath = join(project, ".groundwork", "config.json");
    const runner = await import(pathToFileURL(join(guardsDir, "run.mjs")).href);
    const hook = join(project, ".groundwork", "hooks", "session-start.mjs");
    const orientation = existsSync(hook) ? (await import(pathToFileURL(hook).href)).orientation : undefined;

    // Groundwork's own subagents get their card from the runner, so they skip it.
    await context.session.hook("context", async (input) => {
      if (!orientation || String(input.agent ?? "").startsWith("gw-")) return;
      const text = orientation(project);
      if (text) input.system.push({ type: "text", text });
    });

    await context.tool.hook("execute.before", async (call) => {
      const guards = existsSync(configPath) ? (JSON.parse(readFileSync(configPath, "utf8")).guards ?? []) : [];
      if (guards.length === 0) return;
      const action = runner.toAction("opencode", { tool: call.tool, args: call.input ?? {} });
      if (!action) return;
      const result = await runner.runGuards(action, guards, guardsDir);
      if (result.block) throw new Error(result.reason);
    });
  },
};
`;

// Pure: core files in, OpenCode files out. Generated files point to the core instead of copying it.
export function generateOpenCode(core: CoreFiles, models: ModelHints = {}): Record<string, string> {
  const out: Record<string, string> = {};

  for (const { name, description } of commandsOf(core)) {
    out[`.opencode/commands/${name}.md`] = [
      "---",
      `description: ${yamlValue(description)}`,
      "---",
      `Read \`.groundwork/commands/${name}.md\` now and follow it exactly.`,
      "",
      "Arguments: $ARGUMENTS",
      "",
    ].join("\n");
  }

  for (const { name: role, description } of rolesOf(core)) {
    const deny = ROLE_DENY[role];
    if (!deny) throw new Error(`No OpenCode permissions defined for role "${role}"`);
    const model = modelFor(models, role, "opencode");
    out[`.opencode/agents/gw-${role}.md`] = [
      "---",
      `description: ${yamlValue(description)}`,
      "mode: subagent",
      ...(model ? [`model: ${yamlValue(model)}`] : []),
      ...(deny.length > 0 ? ["permission:", ...deny.map((key) => `  ${key}: deny`)] : []),
      "---",
      `You are the Groundwork ${role}. Read \`.groundwork/roles/${role}.md\` now and follow it exactly.`,
      "Load only the files it lists under Load.",
      "",
    ].join("\n");
  }

  out[".opencode/plugins/groundwork-guards.js"] = GUARD_PLUGIN;

  return sortedByPath(out);
}
