// OpenCode adapter. Formats from opencode.ai/docs (commands, agents, tools, rules), checked 2026-09-24.
// OpenCode reads AGENTS.md itself, so no extra rules file is needed.
import type { CoreFiles } from "../core.js";
import { commandsOf, modelFor, sortedByPath, subagentRolesOf, yamlValue, type ModelHints } from "./shared.js";

// OpenCode permission keys each role's subagent is denied. "edit" covers edit, write and apply_patch.
const ROLE_DENY: Record<string, string[]> = {
  tester: [],
  implementer: [],
  reviewer: ["edit"],
};

// Runs Groundwork's guards before each tool call (throwing blocks the call), records the human's
// own messages for the commit gate, and adds the session-start orientation to the system prompt,
// like Claude Code's SessionStart hook.
// OpenCode 2.x plugin format: a default export { id, setup }, with hooks registered on the context.
// Guards checked against OpenCode 2.0.16 on 2026-09-25. The "context" session hook, whose system
// entries must be { type: "text", text }, checked against 2.0.18 on 2026-09-26. The "prompt" session
// hook (the human's messages) comes from opencode.ai/v2/docs/build/plugins; card 11.2 verifies it
// live before the docs claim parity.
const GUARD_PLUGIN = `// Groundwork: runs the guards listed in .groundwork/config.json before each tool call, records the
// human's own messages for the commit gate, and tells each new session where the project stands
// (from .groundwork/HANDOFF.md).
// Throwing an error blocks the call. Generated by Groundwork; edit .groundwork/guards/ instead.
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

// This file lives in <project>/.opencode/plugins/, so the project is two folders up.
const project = fileURLToPath(new URL("../../", import.meta.url));

export default {
  id: "groundwork-guards",
  setup: async (context) => {
    const guardsDir = join(project, ".groundwork", "guards");
    const runner = await import(pathToFileURL(join(guardsDir, "run.mjs")).href);
    const hook = join(project, ".groundwork", "hooks", "session-start.mjs");
    const orientation = existsSync(hook) ? (await import(pathToFileURL(hook).href)).orientation : undefined;

    // Groundwork's own subagents get their card from the runner, so they skip it.
    await context.session.hook("context", async (input) => {
      if (!orientation || String(input.agent ?? "").startsWith("gw-")) return;
      const text = orientation(project);
      if (text) input.system.push({ type: "text", text });
    });

    // Records the human's messages, like Claude Code's UserPromptSubmit hook. Prompt admission
    // fires for prompts the user (or a command) submits; synthetic messages don't run it. The
    // "records-human" marker is written on the first real message, proving the signal live: only
    // then does the commit gate demand the approvals marker, so a tool without this hook keeps
    // the card checks only.
    try {
      const recorder = join(project, ".groundwork", "hooks", "user-prompt.mjs");
      const { recordHuman } = existsSync(recorder) ? await import(pathToFileURL(recorder).href) : {};
      if (typeof recordHuman === "function") {
        await context.session.hook("prompt", (event) => {
          try {
            recordHuman(project, event?.prompt?.text ?? "");
            const approvals = join(project, ".groundwork", ".approvals");
            mkdirSync(approvals, { recursive: true });
            writeFileSync(join(approvals, "records-human"), JSON.stringify({ tool: "opencode", at: new Date().toISOString() }, null, 2) + "\\n");
          } catch {
            // Best effort: the gate then only checks the card.
          }
        });
      } else if (existsSync(recorder)) {
        console.warn("Groundwork: .groundwork/hooks/user-prompt.mjs doesn't export recordHuman, so the commit gate will check the card only.");
      }
    } catch {
      console.warn("Groundwork: the prompt hook isn't available (OpenCode version or .groundwork/hooks), so the commit gate will check the card only.");
    }

    // The runner fails safe: a broken config blocks commits only, and says why.
    await context.tool.hook("execute.before", async (call) => {
      const result = await runner.evaluate("opencode", { tool: call.tool, args: call.input ?? {} }, guardsDir);
      for (const warning of result.warnings) console.warn(warning);
      if (result.block) throw new Error(result.reason);
    });
  },
};
`;

// Pure: core files in, OpenCode files out. Generated files point to the core instead of copying it.
export function generateOpenCode(core: CoreFiles, models: ModelHints = {}): Record<string, string> {
  const out: Record<string, string> = {};

  for (const { name, description } of commandsOf(core)) {
    out[`.opencode/commands/${name}.md`] = [
      "---",
      `description: ${yamlValue(description)}`,
      "---",
      `Read \`.groundwork/commands/${name}.md\` now and follow it exactly.`,
      "",
      "Arguments: $ARGUMENTS",
      "",
    ].join("\n");
  }

  for (const { name: role, description } of subagentRolesOf(core)) {
    const deny = ROLE_DENY[role];
    if (!deny) throw new Error(`No OpenCode permissions defined for role "${role}"`);
    const model = modelFor(models, role, "opencode");
    out[`.opencode/agents/gw-${role}.md`] = [
      "---",
      `description: ${yamlValue(description)}`,
      "mode: subagent",
      ...(model ? [`model: ${yamlValue(model)}`] : []),
      ...(deny.length > 0 ? ["permission:", ...deny.map((key) => `  ${key}: deny`)] : []),
      "---",
      `You are the Groundwork ${role}. Read \`.groundwork/roles/${role}.md\` now and follow it exactly.`,
      "Load only the files it lists under Load.",
      "",
    ].join("\n");
  }

  out[".opencode/plugins/groundwork-guards.js"] = GUARD_PLUGIN;

  return sortedByPath(out);
}
