// Groundwork: runs the guards listed in .groundwork/config.json before each tool call.
// Throwing an error blocks the call. Generated by Groundwork; edit .groundwork/guards/ instead.
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { pathToFileURL } from "node:url";

export const GroundworkGuards = async ({ directory }) => {
  const guardsDir = join(directory, ".groundwork", "guards");
  const configPath = join(directory, ".groundwork", "config.json");
  const runner = await import(pathToFileURL(join(guardsDir, "run.mjs")).href);

  return {
    "tool.execute.before": async (input, output) => {
      const guards = existsSync(configPath) ? (JSON.parse(readFileSync(configPath, "utf8")).guards ?? []) : [];
      if (guards.length === 0) return;
      const action = runner.toAction("opencode", { tool: input.tool, args: output.args ?? {} });
      if (!action) return;
      const result = await runner.runGuards(action, guards, guardsDir);
      if (result.block) throw new Error(result.reason);
    },
  };
};
